dist: bionic

language: minimal
services:
  - docker

env:
  - >-
    DOCKER_IMAGE=debian:buster RUN_SCRIPT="apt-get update && apt-get install -yq dpkg-dev debhelper && /repofiles/build"

script:
  - >-
    docker run -v $(pwd):/repofiles --rm -ti $DOCKER_IMAGE sh -c "$RUN_SCRIPT"

notifications:
  email: false
